#!/usr/bin/env python3
"""Build Mac Photo Studio sprint release packages.

The release builder creates a reproducible release directory and ZIP archive
from files that already exist in the local repository.
"""

from __future__ import annotations

import argparse
import json
import shutil
import stat
import zipfile
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class ReleaseSpec:
    sprint: str
    codename: str
    release: str
    branch: str
    expected_tests: int
    commit_message: str
    payload_files: tuple[str, ...]

    @property
    def package_name(self) -> str:
        safe_codename = self.codename.replace(" ", "")
        return f"Sprint_{self.sprint.replace('.', '_')}_{safe_codename}_{self.release}"


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _make_executable(path: Path) -> None:
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _copy_payload(repo_root: Path, release_dir: Path, payload_files: tuple[str, ...]) -> None:
    for relative_name in payload_files:
        source = repo_root / relative_name
        if not source.exists():
            raise FileNotFoundError(f"Payload file not found: {relative_name}")

        destination = release_dir / relative_name
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)


def _standard_files(spec: ReleaseSpec) -> dict[str, str]:
    return {
        "README_FIRST.txt": f"""Mac Photo Studio\nSprint {spec.sprint} – {spec.codename} {spec.release}\n\nApply this release from the extracted package directory:\n\n    ./apply.sh\n    ./verify.sh\n\nExpected tests: {spec.expected_tests} passed\n\nCommit message:\n\n    {spec.commit_message}\n""",
        "RELEASE_NOTES.md": f"# Sprint {spec.sprint} – {spec.codename} {spec.release}\n\nGenerated by the Mac Photo Studio Release Builder.\n",
        "CHANGES.md": f"# Changes\n\nPayload files included: {len(spec.payload_files)}\n",
        "VERSION": f"Sprint {spec.sprint} {spec.codename} {spec.release}\n",
        "COMMIT_MESSAGE.txt": spec.commit_message + "\n",
        "release.json": json.dumps(
            {
                "project": "Mac Photo Studio",
                "sprint": spec.sprint,
                "codename": spec.codename,
                "release": spec.release,
                "branch": spec.branch,
                "expected_tests": spec.expected_tests,
                "commit_message": spec.commit_message,
                "payload_files": list(spec.payload_files),
            },
            indent=2,
        )
        + "\n",
    }


def _script_files(spec: ReleaseSpec) -> dict[str, str]:
    payload_lines = "\n".join(f'copy_file "{name}"' for name in spec.payload_files)
    return {
        "apply.sh": f'''#!/usr/bin/env bash
set -euo pipefail
REPO_ROOT="${{MPS_REPO_ROOT:-$HOME/Downloads/mac-photo-studio}}"
PACKAGE_ROOT="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"

if [ ! -d "$REPO_ROOT/.git" ]; then
    echo "ERROR: Repository not found: $REPO_ROOT" >&2
    exit 1
fi

copy_file() {{
    local rel="$1"
    mkdir -p "$REPO_ROOT/$(dirname "$rel")"
    cp "$PACKAGE_ROOT/$rel" "$REPO_ROOT/$rel"
}}

{payload_lines}

echo "Applied Sprint {spec.sprint} – {spec.codename} {spec.release} to $REPO_ROOT"
''',
        "verify.sh": f'''#!/usr/bin/env bash
set -euo pipefail
REPO_ROOT="${{MPS_REPO_ROOT:-$HOME/Downloads/mac-photo-studio}}"
cd "$REPO_ROOT"
python3 -m pytest
''',
        "rollback.sh": f'''#!/usr/bin/env bash
set -euo pipefail
REPO_ROOT="${{MPS_REPO_ROOT:-$HOME/Downloads/mac-photo-studio}}"
cd "$REPO_ROOT"
for rel in {' '.join(spec.payload_files)}; do
    if git ls-files --error-unmatch "$rel" >/dev/null 2>&1; then
        git checkout -- "$rel"
    else
        rm -f "$rel"
    fi
done
echo "Rolled back Sprint {spec.sprint} – {spec.codename} {spec.release} payload files."
''',
        "sanity_check.sh": f'''#!/usr/bin/env bash
set -euo pipefail
REPO_ROOT="${{MPS_REPO_ROOT:-$HOME/Downloads/mac-photo-studio}}"
cd "$REPO_ROOT"
git rev-parse --is-inside-work-tree >/dev/null
python3 --version
echo "Sanity check OK for Sprint {spec.sprint} – {spec.codename} {spec.release}."
''',
    }


def build_release(repo_root: Path, output_root: Path, spec: ReleaseSpec) -> Path:
    repo_root = repo_root.resolve()
    output_root = output_root.resolve()
    release_dir = output_root / spec.package_name

    if release_dir.exists():
        shutil.rmtree(release_dir)
    release_dir.mkdir(parents=True)

    _copy_payload(repo_root, release_dir, spec.payload_files)

    for name, content in _standard_files(spec).items():
        _write_text(release_dir / name, content)

    for name, content in _script_files(spec).items():
        script_path = release_dir / name
        _write_text(script_path, content)
        _make_executable(script_path)

    archive_path = shutil.make_archive(str(release_dir), "zip", output_root, spec.package_name)
    return Path(archive_path)


def load_spec(path: Path) -> ReleaseSpec:
    data = json.loads(path.read_text(encoding="utf-8"))
    return ReleaseSpec(
        sprint=data["sprint"],
        codename=data["codename"],
        release=data["release"],
        branch=data.get("branch", "develop"),
        expected_tests=int(data["expected_tests"]),
        commit_message=data["commit_message"],
        payload_files=tuple(data["payload_files"]),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a Mac Photo Studio sprint release package.")
    parser.add_argument("spec", type=Path, help="Path to release spec JSON")
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--output-root", type=Path, default=Path("dist"))
    args = parser.parse_args()

    spec = load_spec(args.spec)
    archive = build_release(args.repo_root, args.output_root, spec)
    print(archive)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
